### ISSUE TITLE
Enhance Alert Data Model

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#2869]
To enhance the alerting model, alerts are becoming timespans instead of discrete events. For this to work, the data model needs to be extended.
- [x] Add End Timestamp To Data Alert Model (#3072)
- [x] Add Alert Closing Logic To Alert Scanner (#3072)
- [x] Show Old Alarm Histories In Appropriate Way (#3103)
- [ ] Introduce Closing Event In Alarm Callbacks
- [ ] Investigate If Grace Period (Pausing Between Two Alerts) Is Still Needed
- [ ] Update documentation to reflect change

**Comment by phlegx** [comment]
@dennisoelkers Will these changes also enable us to set a  time period and a number of errors/warnings happening during this period? 

Meaning to only send a notification if the number of errors/warnings within a certain time frame are over the threshold an user has set? Similar what ```newrelic``` does?

**Comment by edmundoa** [comment]
Closed in favour of #3178 and #3179.
