### ISSUE TITLE
Improve Alert Management Interface

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#2870]
- [x] Create UI Mockups for improved interface
- [x] Extract Alert Management Page Into Separate Page (#3103)
- [x] Add Overview Of Currently Active Alerts (#3103)
- [ ] Add Most Recent Alerts Dashboard Widget
- [ ] Add Stream Alert Status Dashboard Widget
- [ ] Add Muting Functionality For Streams/Alarm Callbacks/Users
- [x] Add Alert Details Page (#3103)

**Comment by edmundoa** [comment]
Closed in favour of #3181 and #3182.
