### ISSUE TITLE
Improve Alerting

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#2871]
- [x] Refactor/Make Alert Conditions pluggable #2867
- [x] Remove Special Handling Of Email Alarm Callback #2868 
- [x] Migrate alert receivers to Email Alarm Callback #3120
- [ ] Enhance Alert Data Model #2869 
- [ ] Improve Alert Management Interface #2870

**Comment by edmundoa** [comment]
Closed, as all related issues are also closed now.
