### ISSUE TITLE
Alerting open tasks

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3178]
These are some open tasks for alerting in 2.2:

- [x] Check permissions to manage conditions and notifications
- [x] UI refinements
    - [x] Improve conditions forms
    - [x] Ensure everything looks fine when there are no streams
    - [X] Clean up alarm callbacks code (#3205)
- [X] Allow to test a single notification (#3196)
- [X] Ensure the test action fails when email configuration is not set (#3196)
- [x] Investigate if grace period (pausing between two alerts) is still needed (#3346)
