### ISSUE TITLE
Content Packs v2 - Meta Issue

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4225]
This issue collects all issues related to the next version of content packs.

- [ ] "Support parameterized content packs" #4224
- [ ] "Support views in content packs" #4223
- [ ] "Support processing pipelines in content packs" #4222
- [ ] "Allow plugins to support content packs" #4221
- [ ] "Support version contraints for content packs" #4220
- [ ] "Better process to update content packs" #3517
- [ ] "Processing Pipelines cannot be included in Content Packs" #2507 #4222
- [ ] "Content Pack rollback does not rollback the Grok Patterns" #2189
- [ ] "Alerts configuration is not saved when creating a content pack for a stream" #1758
- [ ] "Web UI: Make contents of imported content packs inspectable" #1653
- [ ] "Include licenses in content packs v2?" https://github.com/Graylog2/graylog-plugin-license/issues/34

**Comment by dennisoelkers** [comment]
I think we should turn this into a project, this is what they are for.

**Comment by dennisoelkers** [comment]
I added a project for this: https://github.com/orgs/Graylog2/projects/2. Is there any benefit to keep this open?

**Comment by bernd** [comment]
@dennisoelkers I am fine with closing this one in favor of the project. :+1:

**Comment by etienne-napoleone** [comment]
I can't find this project, where is it currently tracked?
