### ISSUE TITLE
Remove legacy auto content pack loader 

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4940]
The legacy content pack system had a feature that would load **and install** any content pack that exists in the `content_packs_dir` directory. We have been using this to load and install the list of default Grok patterns into graylog on the first server start.

We want to remove the automatic content pack loader in favor of the new content pack system. Users don't seem to use this and we can introduce a better version based on the new content pack system if people really need it.

## Tasks

- [x] Remove [ContentPackLoaderPeriodical](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java) class
- [x] Remove [ContentPackLoaderConfig](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/bundles/ContentPackLoaderConfig.java) class
- [x] Remove content pack loader config from MongoDB (really needed?)
- [x] Remove Content Packs Dir Configuration Option
