### ISSUE TITLE
Move email configuration into cluster config

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6049]
The server email configuration is currently done in the `graylog.conf` file and requires a server restart after changing it. We want to move this configuration into the cluster config so it can be changed from the UI and without restarting the server.

## Tasks

- [ ] Create cluster config object to store email configuration
- [ ] Write migration to store existing email configuration from `graylog.conf`/`server.conf` in the database
- [ ] Create UI component for the "System / Configurations" page to edit the email configuration
- [ ] Switch users of the config file settings over to the new cluster config based settings (e.g. alerting)

**Comment by radykal-com** [comment]
I'd like to help with this one, maybe with the java part, because I don't know enough frontend (React..) to implement the full feature. Can I?

**Comment by radykal-com** [comment]
@bernd can we review the current state of the PR?
