### ISSUE TITLE
Create migration to add events and system-events streams and index sets

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6085]
## Description

The event/alerting system needs a default events index set and a system-events index set. These should be created with a migration during server startup.

## Tasks

-  Create new migration to create
    - [ ] Default events stream
    - [ ] System events stream
    - [ ] Default events index set
    - [ ] System events index set
- [ ] The events and system-events index sets need to be of type `TemplateType.EVENTS`

## Open Questions

- [ ] tbd
