### ISSUE TITLE
Disable old alert system

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6112]
## Description

For the 3.1 release we have to disable the old alert system to avoid having two alerting systems running at the same time.

The actual removal of the old alerts code is tracked in https://github.com/Graylog2/graylog2-server/issues/5919.

## Tasks

- [ ] Make sure the `AlertScannerThread` doesn't get started
- [ ] Check if any other services are running for the old alerts system
- [ ] Think about adding a feature flag that can switch between the old and new alert/event system
- [ ] Remove old alerts from the navigation. See: https://github.com/Graylog2/graylog2-server/issues/6108
