### ISSUE TITLE
Add metrics to events/alerting system

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6196]
The new events/alerting system doesn't implement any metrics, yet.

To be able to debug issues or monitor behavior we have to add metrics to several subsystems.

## Tasks

- Notification execution
  - [x] Meter for success, error and retries
- Event definition execution
  - [x] Counter for executions, success, error and retries (meter is probably not that useful with long intervals between executions)
  - [x] Number of created events per event definition
- Job scheduler
  - [x] Timer for job execution
  - [ ] Meter for exceptions and trigger locks and releases

## Open Questions

- [ ] tbd
