### ISSUE TITLE
Add "source_streams" to events

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6211]
## Description

We need a `source_streams` field in events. This can be used to use permission filters on events based on stream permissions.

## Tasks

- [ ] Add `source_streams` field to event interface and implementations
- [ ] Add `source_streams` field to event index schema
- [ ] Adjust all event processors to fill the `source_streams` field
