### ISSUE TITLE
Event definition field spec name needs validation

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6217]
## Description

It is currently possible to use any string as `name` for a custom field in event definitions. Since the `name` becomes a field in Elasticsearch, we need to apply some validations. (e.g. no whitespace, no special characters)

## Tasks

- [ ] Check which characters can be used in a field name
- [ ] Implement backend validation for the field spec
- [ ] implement UI validation for the field spec

## Open Questions

- [ ] tbd

**Comment by edmundoa** [comment]
I'm working on at least a simple version of this as part of #6153.

**Comment by bernd** [comment]
Closed in #6153
