### ISSUE TITLE
Run database migrations before services start

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6671]
Our database migrations are currently executed by the `Periodicals` sub-system. That means they execute at some point after the periodicals system has started. This is an issue because some services might start before the migrations have been executed and run into problems.

Examples:

- https://github.com/Graylog2/graylog2-server/issues/6414
- https://github.com/Graylog2/graylog2-server/pull/6643

To fix this, the database migrations should be executed **before** other services start.

Ideally we should also move the index creation out of the database services into a migration or a separate step during the bootstrap process. Right now the database indices are created on every instance creation of the database services.

Refs https://github.com/Graylog2/graylog2-server/issues/5248

## Tasks

- [ ] Remove database migrations from `Periodicals`
- [ ] Execute migrations before starting other services in the bootstrap process
- [ ] Move creation of database indices into migrations as well or create a separate phase for that

**Comment by mpfz0r** [comment]
Partly done with #11526
