### ISSUE TITLE
Track message size as system message field

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#6838]
## What?
Graylog uses a certain algorithm to keep track of the size of a message, which is the basis for traffic accounting (https://docs.graylog.org/en/3.1/pages/enterprise/setup.html#details-on-license-verification and https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L569-L571).
This value should be tracked in Graylog as a system level field.

## Why?
In order to find out which sources send how much data to Graylog (for internal accounting, debugging or purely informational purposes), it makes sense to use Graylog's own features to build searches and dashboards instead of implementing analysis functions tailored to only message size accounting.

## Tasks

- [ ] Add `gl2_accounted_message_size` field as `long` to index mapping (so it's not getting auto-created as `keyword`/`string`)
- [ ] Serialize message size into `gl2_accounted_message_size` field when writing to ES
- [ ] Write upgrade notes to add `gl2_accounted_message_size` field to active write index mappings (must be done before upgrading to 3.2)

## Your Environment

* Graylog Version: 3.2

**Comment by bernd** [comment]
We will probably use `gl2_accounted_message_size` as a field name.
