### ISSUE TITLE
Implement URL white list service

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6853]
## Description

When non-admin users have permissions to configure a lookup data adapter, they can use the `HTTPJSONPath` adapter to query potentially sensitive information. (e.g. EC2 instance metadata in AWS) The `HTTPJSONPath` data adapter executes a HTTP request for an URL that is defined by the user that configures the data adapter.

This is **only** an issue if an admin user is giving lookup-table permissions to a regular user. This is not the default.

To mitigate this issue, we want to implement an URL whitelist service. This service can be used by other subsystems that deal with user defined URLs to check if an URL is allowed to be used. The whitelist service requires a separate set of permissions to make sure users can be given permission to create/modify lookup tables but are not allowed to modify the URL whitelist.

## Tasks

- [x] Must be enabled by default
- [x] Support different match types
  - Regexp
  - Literal string
- [x] Separate permissions for the whitelist service
- [x] Check URLs at runtime
- [x] Configuration UI on "System/Configuration" page
- ~~[UI form component for URL whitelist that shows good error message and option to add new URL to whitelist (if user has permission).~~ This was moved to #7169
- [x] Use white list service in lookup data adapters (e.g. `HTTPJSONPath`, `DSVHTTP`) and event notifications
- [x] Create system notification when a runtime URL check failed
- [x] Create migration to add URL from known entities to the white list (e.g. lookup adapters, event notifications)
- [x] Backport to 3.1.x
- [x] Content pack support
- [x] Documentation

**Comment by thll** [comment]
We'll enable the whitelist by default. Should we add an option on the whitelist configuration page to disable the whitelist altogether if users don't want to be bothered with whitelisting?
Even without an explicit option the user can still easily create a catch-all whitelist by adding a regex like `.*`. But that might not be convenient enough.

**Comment by thll** [comment]
Reopening as there are some tasks left to be addressed.

**Comment by bernd** [comment]
@thll Can you please create a new issue for the remaining tasks so we can close this issue for 3.1.4? Thank you! :smiley:

**Comment by thll** [comment]
> @thll Can you please create a new issue for the remaining tasks so we can close this issue for 3.1.4? Thank you! 😃

Sure, I created  #7169 for this.

**Comment by bernd** [comment]
Done! Thank you!
