### ISSUE TITLE
Update to the latest MongoDB Java driver

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7142]
## Description

We are currently stuck with the 3.6 version of the MongoDB Java driver because the testing framework we use doesn't work with never versions. (https://github.com/fakemongo/fongo/issues/357, https://github.com/fakemongo/fongo/issues/367)

The mongojack version we are using (2.10.0 as of this writing) already works with the 3.8 MongoDB Java driver. The latest mongojack version (2.10.1 as of this writing) even supports the 3.11 version.

Since the fongo library doesn't seem to be maintained anymore, we should probably move all tests that use fongo (and nosqlunit) over to the new testcontainers based testing infrastructure we already have in place. We even get the benefit of testing with a real MongoDB server and could also test different MongoDB server versions.

## Tasks

- [ ] Replace all fongo/nosqlunit usage with testcontainers (see [MongoDBInstance](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBInstance.java) and [MongoDBInstanceTest](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBInstanceTestIT.java))
- [ ] Check if https://github.com/mongojack/mongojack works with the latest version or use a version that works with it
- [ ] Check if anything else doesn't work with a newer MongoDB Java driver version
- [ ] Update documentation on https://docs.graylog.org/ with the supported MongoDB versions

**Comment by radykal-com** [comment]
Can I check this one?

**Comment by bernd** [comment]
@radykal-com Feel free to take a shot at it. It will be a lot of work, though. :smile: Thank you!

**Comment by radykal-com** [comment]
Yaah... I started yesterday, lots of files to change, also some rework of the new MongoDBInstance will be required to load fixtures from multiple files or new composite fixtures will be required for some tests. I will need some time :)

**Comment by bernd** [comment]
@radykal-com Loading fixtures from multiple files already works: `@MongoDBFixtures({"file1.json", "file2.json"})`

**Comment by radykal-com** [comment]
Woo, thanks you.

Checklist of some things I'm finding during the task that will need extra work

- [ ]  Replacement for `@ShouldMatchDataSet`
- [ ]  Replacement for `@CustomComparisonStrategy(comparisonStrategy = MongoFlexibleComparisonStrategy.class)`
