### ISSUE TITLE
Migrate existing streams and dashboard roles and permissions into grants

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#8594]
## Description

The existing streams and dashboard roles need to be migrated into the new grants system.

For every dashboard or stream permission in an existing role, we create grants for each user that has the role assigned. The migrated permissions will be removed from the role. If the role doesn't have any permissions left after the migration, the role will be removed from each user and deleted.

## Tasks

- [x] Explode role permissions into grants for each user
- [x] Remove stream and dashboard permissions from migrated roles
- [x] Remove role from assigned users and delete role when there are no permissions left in a role
- [ ] Migrate stream and dashboard permissions in user objects into grants
